mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('restaurant.urls',namespace='res'))
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = "res";

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
]

restaurant/models.py
from django.db import models

# Create your models here.

restaurant/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

def contact(request):
    return render(request,'contact.html')

restaurant/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Restaurant - About{% endblock title %}
{% block content %}
    <div class="title abt">
       <h1>About Us</h1>
    </div>
    <div class="about__content">
        <img src="{% static 'images/about.jpg' %}" alt="" srcset="">
        <div>
            <h1>About Us</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem vitae exercitationem voluptates consequuntur id maxime rerum soluta pariatur culpa repudiandae, tenetur, quae nemo veritatis accusantium in expedita autem delectus enim officia. Numquam mollitia, quo quia dignissimos hic asperiores nisi sequi sunt quasi recusandae, minus provident rerum tempore dicta autem reprehenderit corrupti dolor, fugit harum tenetur. Ullam nesciunt quaerat beatae adipisci qui quia necessitatibus quisquam, soluta totam? Delectus repellendus rerum magnam molestiae doloremque labore nisi nostrum molestias dolore, pariatur sapiente, illum, ducimus magni amet obcaecati similique itaque sequi necessitatibus? Sint, iste aperiam explicabo ad at eum veritatis delectus natus quisquam maxime.</p>
        </div>
    </div>  
{% endblock content %}

restaurant/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div id="content">
        {% block content %}{% endblock content %}
    </div>
  </body>
</html>

restaurant/templates/contact.html
{% extends 'base.html' %} {% load static %} {% block title %}Restaurant -
Contact{% endblock title %} {% block content %}
<div class="title">
  <h1>Contact Us</h1>
</div>
<div class="contact__content abt">
  <img src="{% static 'images/contact.jfif' %}" alt="" />
  <div>
    <h1>Reach Us...</h1>
    <ul>
      <li><span>Phone</span>: +91 123456789</li>
      <li><span>Email</span>: example@example.com</li>
      <li><span>Address</span>: XYZ, Mars, Milkyway Galaxy..</li>
    </ul>
  </div>
</div>
{% endblock content %}

restaurant/templates/home.html
{% extends 'base.html' %} {% block title %}Restaurant - Home{% endblock title %}
{% load static %}
{% block content %}
<div class="hero">
  <div class="image">
    <img
      src="{% static 'images/main.webp' %}"
      alt="Background"
    />
  </div>
</div>
<div class="title">
  <h1>Grand Hyatt</h1>
</div>
<p class="description">
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur, laudantium
  magni fuga quibusdam, vel eum sit unde quos quae similique architecto quas?
  Consequatur, officiis quas. Fugit aspernatur sequi inventore laborum, mollitia
  exercitationem amet nemo officia sapiente, explicabo nostrum ratione, itaque
  voluptatem repellat doloremque. Labore, ex. Ea commodi modi culpa facere
  repudiandae recusandae amet, provident quaerat esse laudantium. Aliquam
  sapiente accusamus exercitationem voluptatum veritatis pariatur, similique
  doloribus veniam nostrum, dolor ad modi, repellat aspernatur quis odit
  asperiores ab ullam praesentium laborum reiciendis ea necessitatibus officia
  eaque totam? Ratione nisi, tempore corrupti eaque, repellat dolores et
  excepturi soluta optio dolor, eius aliquam.
</p>
{% endblock content %}

restaurant/templates/navbar.html
<nav class="nav">
    <ul>
        <li><a href="{% url 'res:index' %}">Home</a></li>
        <li><a href="{% url 'res:about' %}">About</a></li>
        <li><a href="{% url 'res:contact' %}">Contact</a></li>
    </ul>
</nav>